# Generated by Django 4.1 on 2022-08-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_rating_like_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toys',
            new_name='Toy',
        ),
    ]
