# Generated by Django 4.1 on 2022-08-23 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toys', '0003_rename_toys_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='toys',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='product',
            new_name='toys',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='toys',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='toys.toy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
